[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8889
  targetPort = 3000
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
